// Ülke Bayrakları (Unicode Flag Emojileri)
// Popüler 50 ülke

export const countryFlags = [
  { id: 1, name: 'Türkiye', flag: '🇹🇷' },
  { id: 2, name: 'Amerika Birleşik Devletleri', flag: '🇺🇸' },
  { id: 3, name: 'Almanya', flag: '🇩🇪' },
  { id: 4, name: 'Fransa', flag: '🇫🇷' },
  { id: 5, name: 'İngiltere', flag: '🇬🇧' },
  { id: 6, name: 'İtalya', flag: '🇮🇹' },
  { id: 7, name: 'İspanya', flag: '🇪🇸' },
  { id: 8, name: 'Rusya', flag: '🇷🇺' },
  { id: 9, name: 'Çin', flag: '🇨🇳' },
  { id: 10, name: 'Japonya', flag: '🇯🇵' },
  { id: 11, name: 'Güney Kore', flag: '🇰🇷' },
  { id: 12, name: 'Hindistan', flag: '🇮🇳' },
  { id: 13, name: 'Brezilya', flag: '🇧🇷' },
  { id: 14, name: 'Arjantin', flag: '🇦🇷' },
  { id: 15, name: 'Meksika', flag: '🇲🇽' },
  { id: 16, name: 'Kanada', flag: '🇨🇦' },
  { id: 17, name: 'Avustralya', flag: '🇦🇺' },
  { id: 18, name: 'Yeni Zelanda', flag: '🇳🇿' },
  { id: 19, name: 'Güney Afrika', flag: '🇿🇦' },
  { id: 20, name: 'Mısır', flag: '🇪🇬' },
  { id: 21, name: 'Suudi Arabistan', flag: '🇸🇦' },
  { id: 22, name: 'İran', flag: '🇮🇷' },
  { id: 23, name: 'İsrail', flag: '🇮🇱' },
  { id: 24, name: 'Yunanistan', flag: '🇬🇷' },
  { id: 25, name: 'Hollanda', flag: '🇳🇱' },
  { id: 26, name: 'Belçika', flag: '🇧🇪' },
  { id: 27, name: 'İsviçre', flag: '🇨🇭' },
  { id: 28, name: 'Avusturya', flag: '🇦🇹' },
  { id: 29, name: 'Polonya', flag: '🇵🇱' },
  { id: 30, name: 'Ukrayna', flag: '🇺🇦' },
  { id: 31, name: 'İsveç', flag: '🇸🇪' },
  { id: 32, name: 'Norveç', flag: '🇳🇴' },
  { id: 33, name: 'Danimarka', flag: '🇩🇰' },
  { id: 34, name: 'Finlandiya', flag: '🇫🇮' },
  { id: 35, name: 'Portekiz', flag: '🇵🇹' },
  { id: 36, name: 'Romanya', flag: '🇷🇴' },
  { id: 37, name: 'Çekya', flag: '🇨🇿' },
  { id: 38, name: 'Macaristan', flag: '🇭🇺' },
  { id: 39, name: 'Tayland', flag: '🇹🇭' },
  { id: 40, name: 'Vietnam', flag: '🇻🇳' },
  { id: 41, name: 'Endonezya', flag: '🇮🇩' },
  { id: 42, name: 'Malezya', flag: '🇲🇾' },
  { id: 43, name: 'Singapur', flag: '🇸🇬' },
  { id: 44, name: 'Filipinler', flag: '🇵🇭' },
  { id: 45, name: 'Pakistan', flag: '🇵🇰' },
  { id: 46, name: 'Bangladeş', flag: '🇧🇩' },
  { id: 47, name: 'Şili', flag: '🇨🇱' },
  { id: 48, name: 'Kolombiya', flag: '🇨🇴' },
  { id: 49, name: 'Peru', flag: '🇵🇪' },
  { id: 50, name: 'İrlanda', flag: '🇮🇪' },
];
