// Ülke - Başkent eşleştirmeleri
// countryFlags ile uyumlu (aynı ülke listesi)

export const countryCapitals = [
  { id: 1, country: 'Türkiye', capital: 'Ankara' },
  { id: 2, country: 'Amerika Birleşik Devletleri', capital: 'Washington' },
  { id: 3, country: 'Almanya', capital: 'Berlin' },
  { id: 4, country: 'Fransa', capital: 'Paris' },
  { id: 5, country: 'İngiltere', capital: 'Londra' },
  { id: 6, country: 'İtalya', capital: 'Roma' },
  { id: 7, country: 'İspanya', capital: 'Madrid' },
  { id: 8, country: 'Rusya', capital: 'Moskova' },
  { id: 9, country: 'Çin', capital: 'Pekin' },
  { id: 10, country: 'Japonya', capital: 'Tokyo' },
  { id: 11, country: 'Güney Kore', capital: 'Seul' },
  { id: 12, country: 'Hindistan', capital: 'Yeni Delhi' },
  { id: 13, country: 'Brezilya', capital: 'Brasília' },
  { id: 14, country: 'Arjantin', capital: 'Buenos Aires' },
  { id: 15, country: 'Meksika', capital: 'Meksiko' },
  { id: 16, country: 'Kanada', capital: 'Ottawa' },
  { id: 17, country: 'Avustralya', capital: 'Kanberra' },
  { id: 18, country: 'Yeni Zelanda', capital: 'Wellington' },
  { id: 19, country: 'Güney Afrika', capital: 'Pretoria' },
  { id: 20, country: 'Mısır', capital: 'Kahire' },
  { id: 21, country: 'Suudi Arabistan', capital: 'Riyad' },
  { id: 22, country: 'İran', capital: 'Tahran' },
  { id: 23, country: 'İsrail', capital: 'Kudüs' },
  { id: 24, country: 'Yunanistan', capital: 'Atina' },
  { id: 25, country: 'Hollanda', capital: 'Amsterdam' },
  { id: 26, country: 'Belçika', capital: 'Brüksel' },
  { id: 27, country: 'İsviçre', capital: 'Bern' },
  { id: 28, country: 'Avusturya', capital: 'Viyana' },
  { id: 29, country: 'Polonya', capital: 'Varşova' },
  { id: 30, country: 'Ukrayna', capital: 'Kiev' },
  { id: 31, country: 'İsveç', capital: 'Stockholm' },
  { id: 32, country: 'Norveç', capital: 'Oslo' },
  { id: 33, country: 'Danimarka', capital: 'Kopenhag' },
  { id: 34, country: 'Finlandiya', capital: 'Helsinki' },
  { id: 35, country: 'Portekiz', capital: 'Lizbon' },
  { id: 36, country: 'Romanya', capital: 'Bükreş' },
  { id: 37, country: 'Çekya', capital: 'Prag' },
  { id: 38, country: 'Macaristan', capital: 'Budapeşte' },
  { id: 39, country: 'Tayland', capital: 'Bangkok' },
  { id: 40, country: 'Vietnam', capital: 'Hanoi' },
  { id: 41, country: 'Endonezya', capital: 'Cakarta' },
  { id: 42, country: 'Malezya', capital: 'Kuala Lumpur' },
  { id: 43, country: 'Singapur', capital: 'Singapur' },
  { id: 44, country: 'Filipinler', capital: 'Manila' },
  { id: 45, country: 'Pakistan', capital: 'İslamabad' },
  { id: 46, country: 'Bangladeş', capital: 'Dakka' },
  { id: 47, country: 'Şili', capital: 'Santiago' },
  { id: 48, country: 'Kolombiya', capital: 'Bogotá' },
  { id: 49, country: 'Peru', capital: 'Lima' },
  { id: 50, country: 'İrlanda', capital: 'Dublin' },
];
