// Coğrafya anahtar kelimeleri - ÖSYM / YKS için kritik kavramlar

export const GEOGRAPHY_KEYWORDS = [
  { term: 'Enlem', definition: 'Ekvatora paralel, doğu-batı yönünde uzanan hayali çizgiler. 0°–90° kuzey ve güney.' },
  { term: 'Boylam', definition: 'Kutupları birleştiren, kuzey-güney yönünde uzanan hayali çizgiler. Başlangıç meridyeni Greenwich (0°).' },
  { term: 'Ekvator', definition: 'Dünyayı kuzey ve güney yarımküreye bölen, 0° enlem çizgisi.' },
  { term: 'Yerel Saat', definition: 'Her meridyenin kendi güneşe göre belirlediği saat. 15° meridyen = 1 saat fark.' },
  { term: 'Uluslararası Tarih Değişim Çizgisi', definition: '180° boylamı. Batıya geçince 1 gün ileri, doğuya geçince 1 gün geri.' },
  { term: 'İklim', definition: 'Bir bölgenin uzun süreli (30+ yıl) ortalama hava koşulları.' },
  { term: 'Hava Durumu', definition: 'Kısa süreli (günler) atmosfer koşulları.' },
  { term: 'Biyom', definition: 'Belirli iklim ve bitki örtüsüne sahip büyük ekosistem bölgeleri (ör: tundra, yağmur ormanı).' },
  { term: 'Erozyon', definition: 'Toprak ve kayaların su, rüzgar vb. ile aşınması ve taşınması.' },
  { term: 'Heyelan', definition: 'Toprak veya kayaların eğim aşağı kayması.' },
  { term: 'Tektonik Hareket', definition: 'Yer kabuğundaki levha hareketleri. Deprem, dağ oluşumu, volkanizma nedenidir.' },
  { term: 'Nüfus Yoğunluğu', definition: 'Belirli bir alandaki toplam nüfusun o alana bölünmesi (kişi/km²).' },
  { term: 'Göç', definition: 'İnsanların bir yerden başka bir yere kalıcı veya geçici olarak taşınması.' },
  { term: 'Urbanizasyon', definition: 'Şehirleşme. Kırdan kente nüfus kayması süreci.' },
  { term: 'Delta', definition: 'Akarsuların denize veya göle döküldüğü yerde oluşan üçgen biçimli alüvyal ova.' },
  { term: 'Plato', definition: 'Çevresine göre yüksekte kalan, geniş düz veya hafif engebeli yüzey.' },
  { term: 'Ova', definition: 'Deniz seviyesine yakın, düz veya hafif eğimli geniş düzlük.' },
  { term: 'Dağ', definition: 'Çevresine göre belirgin yükselti farkı olan, eğimli yüzeyli yeryüzü şekli.' },
  { term: 'Körfez', definition: 'Karanın içine sokulan deniz kısmı.' },
  { term: 'Yarımada', definition: 'Üç tarafı suyla çevrili kara parçası.' },
  { term: 'Boğaz', definition: 'İki kara parçasını veya iki denizi birbirine bağlayan dar su geçidi.' },
  { term: 'Kanal', definition: 'İki su kütlesini birleştiren insan yapımı su yolu.' },
  { term: 'Rüzgâr', definition: 'Yatay yönde hareket eden hava akımı.' },
  { term: 'Muson', definition: 'Mevsimlik yön değiştiren, Hint Okyanusu ve Asya\'da etkili rüzgâr sistemi.' },
  { term: 'Alize Rüzgârları', definition: '30° enlemlerden ekvatora doğru esen sürekli rüzgârlar.' },
];
